### POST BOOKING
POST http://localhost:3000/booking HTTP/1.1
content-type: application/json

{
    "conselor_id": "5f8f7f2d0f7a7e2b3c6f8b5d",
    "kode_pembayaran": "kjnda123123",
    "tanggal_konseling": "2020-12-12"
}

### GET BOOKING
GET http://localhost:3000/booking HTTP/1.1


### POST NEW CONSELOR
POST http://localhost:3000/review/conselor HTTP/1.1

### GET REVIEW BY CONSELOR ID
GET http://localhost:3000/review/65617455f242c60a1e550ae5 HTTP/1.1

### POST NEW RATE by conselor id
POST http://localhost:3000/review/65617455f242c60a1e550ae5 HTTP/1.1
Content-Type: application/json

{
    "user_id" : "5f8f7f2d0f7a7e2b3c6f8b5d",
    "rate": 3,
    "comment": "biasa ja"
}

### UPDATE RATE BY ID
PUT http://localhost:3000/review/65617455f242c60a1e550ae5/65617488f242c60a1e550ae9 HTTP/1.1
Content-Type: application/json

{
    "rate" : 1,
    "comment": "jelek banget",
    "user_id" : "5f8f7f2d0f7a7e2b3c6f8b5d"
}


### DELETE REVIEW BY ID
DELETE http://localhost:3000/review/65617455f242c60a1e550ae5/656174a6f242c60a1e550af5 HTTP/1.1